### ISSUE TITLE
[MembersJS] Activation email received twice during signup

### ISSUE THREAD

**Issue by peterzimon** [TryGhost/members.js#23] opened 2020-04-30 14:26 UTC
As the last step of signing up for a paid account (anonymous flow) I received the activation/confirmation email twice. The intended behaviour would be to receive a single email.

**Comment by rishabhgrg** [comment] 2020-06-03 05:24
Closing as unable to reproduce anymore, will re-open if it shows up again.

**Closed by rishabhgrg** 2020-06-03 05:24 UTC
Labels: bug
